### ISSUE TITLE
Need to develop a Lumina program

### ISSUE THREAD

**Issue by aksum3** [NotAdam/Lumina#28]
I have the special Korean FFXIV client and the developers intentionally removed English from the sqpack (quest sheets, etc.).  I would like you to develop a program with Lumina which can replace these with the matching data from the NA FFXIV client.

I tried just swapping files 0x0a data files, but the Korean client would not load.

Ping @NotAdam or anyone who has the ability to take this job on, name your price.

**Comment by NotAdam** [comment]
what the fuck, no, play the global version instead
