### ISSUE TITLE
Pet Action Heal/Place?

### ISSUE THREAD

**Issue by jundong321** [NotAdam/Lumina#54]
I can't find Heal/Place action in both generated sheets [Action](https://www.fuget.org/packages/Lumina.Excel/6.2.1/lib/net6.0/Lumina.Excel.dll/Lumina.Excel.GeneratedSheets/Action) and [PetAction](https://www.fuget.org/packages/Lumina.Excel/6.2.1/lib/net6.0/Lumina.Excel.dll/Lumina.Excel.GeneratedSheets/PetAction). Could you point me to where they are, or resolve them in the sheets?

**Comment by Caraxi** [comment]
`<PetAction>.GetRow(2)`
`<PetAction>.GetRow(3)`
